--- 
services: 
  database: 
    image: "postgres:9.6"
    ports: 
      - "32780:5432"
    volumes: 
      - "./plpr-docker-database-data:/var/lib/postgresql/data"
  web: 
    build: "."
    environment: 
      DATABASE_URL: "postgres://postgres:@database"
    links: 
      - database
    ports: "-\"8899:8000\""
version: "2"